title = "This is only a DEMO of a report!";
expl0 = "What you see now is an example of a report, that can be generated by the application at the end of the test.";
expl1 = "Authors of specific tests can design this page in any way they want it. It is possible to embed many types of data and media in this report, like these two random graphs below.";
expl2 = "Report templates, such as this one, are created with HTML, JavaScript and CSS, just like typical web pages. This demo report uses jQuery library (http://jquery.com/) and Protovis library (http://mbostock.github.io/protovis/) which allowed to create the above graphs. Also, other JavaScript libraries can be used.";
expl3 = "After some real tests are performed, the application will provide the report with actual results of the tests. Authors of the tests should design this report so that it presents the results in a reasonable manner.";
expl4 = "The report can contain multiple pages, and also may contain interactive elements. For instance, try pressing the button below.";
expl5 = "The application allows you to not only view the report. You can also store it as PDF file, print, or send it via email. Of course, when stored as a plain file, the report loses all its interactivity. Authors of the reports can specify the contents and styles that will be saved to the PDF file, to ensure that the final result contains all relevant data.";
msg0 = "Got it!\n\nOf course, this is just a simple message, but this button could have performed any action. For instance, it could reload the graphs with new data, update the text of the report, or switch the view to another page of the report.";

